# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"






gem "colorize", "~> 0.8.1"

gem "tty-prompt", "~> 0.23.0"

gem "rspec", "~> 3.10"

gem "tty-progressbar", "~> 0.17.0"


%w[rspec-core rspec-expectations rspec-mocks rspec-support].each do |lib|
    gem lib, :git => "https://github.com/rspec/#{lib}.git", :branch => 'master'
  end